-- initially created 2013-03-10 by mg

drop table if exists authority;
drop table if exists persistent_login;
drop table if exists scheduled_registration_mail;
drop table if exists scheduled_password_reset_mail;
drop table if exists todoitem;
drop table if exists todolist;
drop table if exists quot_quote;
drop table if exists qaut_quote_author;
drop table if exists qtag_quote_tag;
drop table if exists user;

create table user (
  user_id                    varchar(128)   not null primary key, -- the email of the user
  password                   varchar(80)    not null,
  enabled                    boolean        default 1 not null,
  registrationtoken          varchar(128)   default null,
  registered_since           timestamp      default current_timestamp not null,
  passwordresettoken         varchar(128)   default null,
  passwordreset_requested_at timestamp      default null
);

create table authority (
  user_id   varchar(128) not null,
  authority varchar(50)  not null
);

alter table authority add foreign key (user_id) references user (user_id)
  on delete cascade;

create unique index idx_authority_user_id on authority (user_id, authority);

create table persistent_login (
  user_id   varchar(128) not null,
  series    varchar(64)  primary key,
  token     varchar(64)  not null,
  last_used timestamp    not null
);

alter table persistent_login add foreign key (user_id) references user (user_id)
  on delete cascade;

create table scheduled_registration_mail (
  id            bigint          generated by default as identity(start with 1) not null primary key,
  user_id       varchar(128)    not null,
  url           varchar(1024)   not null,
  attempts      int             default 1 not null,
  firstattempt  timestamp       default current_timestamp not null,
  lastattempt   timestamp       default current_timestamp not null
);

alter table scheduled_registration_mail add foreign key (user_id) references user (user_id)
  on delete cascade;

create table scheduled_password_reset_mail (
  id            bigint          generated by default as identity(start with 1) not null primary key,
  user_id       varchar(128)    not null,
  url           varchar(1024)   not null,
  attempts      int             default 1 not null,
  firstattempt  timestamp       default current_timestamp not null,
  lastattempt   timestamp       default current_timestamp not null
);

alter table scheduled_password_reset_mail add foreign key (user_id) references user (user_id)
  on delete cascade;

-- *****************************************
-- Application specific schema follows here:
-- *****************************************

create table todolist (
  id            bigint          generated by default as identity(start with 1) not null primary key,
  user_id       varchar(128)    not null, -- TOOD ignore case
  listname      varchar(64)     not null,
  created       timestamp       default current_timestamp not null
);

alter table todolist add foreign key (user_id) references user (user_id);
create unique index idx_todolist_user_listname on todolist (user_id, listname);

create table todoitem (
  id            bigint          generated by default as identity(start with 1) not null primary key,
  todolist_id   bigint          not null,
  itemname      varchar(64)     not null,
  created       timestamp       default current_timestamp not null,
  done          boolean         default 0 not null
);

alter table todoitem add foreign key (todolist_id) references todolist (id);

-- *****************************************
-- Application specific schema follows here:
-- *****************************************

create table qaut_quote_author (
  qaut_id       bigint          generated by default as identity(start with 1) not null primary key,
  user_id       varchar(128)    not null,
  author        varchar(64)     not null,
  description   varchar(1024)   default '',
  created       timestamp       default current_timestamp not null,
  updated       timestamp       default current_timestamp not null
);

alter table qaut_quote_author add foreign key (user_id) references user (user_id)
  on delete cascade;

create unique index idx_qaut_quote_user_author on qaut_quote_author (user_id, author);

create table qtag_quote_tag (
  qtag_id         bigint          generated by default as identity(start with 1) not null primary key,
  user_id         varchar(128)    not null,
  tag             varchar(64)     not null,
  created         timestamp       default current_timestamp not null
);

create unique index idx_qtag_quote_user_tag on qtag_quote_tag (user_id, tag);

alter table qtag_quote_tag add foreign key (user_id) references user (user_id)
  on delete cascade;

create table quot_quote (
  quot_id         bigint          generated by default as identity(start with 1) not null primary key,
  user_id         varchar(128)    not null,
  qaut_id         bigint          default null,
  qtag_id         bigint          default null,
  quote           varchar(1024)   default '' not null,
  created         timestamp       default current_timestamp not null,
  updated         timestamp       default current_timestamp not null
);

alter table quot_quote add foreign key (user_id) references user (user_id)
  on delete cascade;

alter table quot_quote add foreign key (qaut_id) references qaut_quote_author (qaut_id)
  on delete set null;

alter table quot_quote add foreign key (qtag_id) references qtag_quote_tag (qtag_id)
  on delete set null;

-- EOF
