-- created 2013-03-10 by mg

drop table if exists authorities;
drop table if exists persistent_logins;
drop table if exists scheduled_registration_mail;
drop table if exists scheduled_password_reset_mail;
drop table if exists todoitem;
drop table if exists todolist;
drop table if exists users;

create table users (
  email                      varchar(128)   not null primary key,
  password                   varchar(80)    not null,
  enabled                    boolean        default 1 not null,
  registrationtoken          varchar(128)   default null,
  registered_since           timestamp      default current_timestamp not null,
  passwordresettoken         varchar(128)   default null,
  passwordreset_requested_at timestamp      default null
);

create table authorities (
  email     varchar(128) not null,
  authority varchar(50)  not null
);

alter table authorities add foreign key (email) references users (email)
  on delete cascade;

create unique index idx_authorities_email on authorities (email, authority);

create table persistent_logins (
  username  varchar(128) not null,
  series    varchar(64)  primary key,
  token     varchar(64)  not null,
  last_used timestamp    not null
);

alter table persistent_logins add foreign key (username) references users (email)
  on delete cascade;

create table scheduled_registration_mail (
  id            bigint          generated by default as identity(start with 1) not null primary key,
  email         varchar(128)    not null,
  url           varchar(1024)   not null,
  attempts      int             default 1 not null,
  firstattempt  timestamp       default current_timestamp not null,
  lastattempt   timestamp       default current_timestamp not null
);

alter table scheduled_registration_mail add foreign key (email) references users (email)
  on delete cascade;

create table scheduled_password_reset_mail (
  id            bigint          generated by default as identity(start with 1) not null primary key,
  email         varchar(128)    not null,
  url           varchar(1024)   not null,
  attempts      int             default 1 not null,
  firstattempt  timestamp       default current_timestamp not null,
  lastattempt   timestamp       default current_timestamp not null
);

alter table scheduled_password_reset_mail add foreign key (email) references users (email)
  on delete cascade;

-- *****************************************
-- Application specific schema follows here:
-- *****************************************

create table todolist (
  id            bigint          generated by default as identity(start with 1) not null primary key,
  username      varchar(128)    not null, -- TOOD ignore case
  listname      varchar(64)     not null,
  created       timestamp       default current_timestamp not null
);

alter table todolist add foreign key (username) references users (email);
create unique index idx_todolist_user_listname on todolist (username, listname);

create table todoitem (
  id            bigint          generated by default as identity(start with 1) not null primary key,
  todolist_id   bigint          not null,
  itemname      varchar(64)     not null,
  created       timestamp       default current_timestamp not null,
  done          boolean         default 0 not null
);

alter table todoitem add foreign key (todolist_id) references todolist (id);

-- EOF
